# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow is meant for as a basic CI run covering the most-important features
# and default Java version. It is meant to run before a PullRequest is merged.

name: "Flink CI (on push)"


on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch the extended workflow should run on."
        required: true
        default: "master"
        type: string
  schedule:
    - cron: '0 1,6,11,16 * * *'

permissions: read-all

jobs:
  basic-qa:
    name: "Basic Source Code Analysis"
    uses: ./.github/workflows/source-code-analysis.yml
    with:
      branch: ${{ inputs.branch }}
  ci:
    name: "Flink CI (Java 8/Scala 2.12/Hadoop 2.10.2)"
    uses: ./.github/workflows/flink-ci-template.yml
    with:
      branch: ${{ inputs.branch }}
      environment: 'PROFILE="-Dflink.hadoop.version=2.10.2 -Dinclude_hadoop_aws"'
      jdk-version: 8
    secrets:
      s3_bucket: ${{ secrets.IT_CASE_S3_BUCKET }}
      s3_access_key: ${{ secrets.IT_CASE_S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.IT_CASE_S3_SECRET_KEY }}
